import json
from pathlib import Path
R = Path("results/research/portfolio/fund_products_20261005")
for tag in ("report_equal_capital_snapshot", "report"):
    s = json.loads((R/tag/"study.json").read_text(encoding="utf-8")); b = json.loads((R/tag/"battery.json").read_text(encoding="utf-8"))
    e = json.loads((R/tag/"exposure.json").read_text(encoding="utf-8")); c = json.loads((R/tag/"capacity.json").read_text(encoding="utf-8"))
    d = json.loads((R/tag/"defensive.json").read_text(encoding="utf-8")); v = json.loads((R/tag/"versus.json").read_text(encoding="utf-8"))
    print("=====", tag)
    bk = s["books"]["GR1"]; print(bk["weights"]); print({k: round(bk["q"][k],5) for k in ("cagr","vol","xs","dd","worst_year","worst_crisis","sortino","xs_monthly")}, bk["tails"]["p20"], bk["tails_plus5"]["p20"])
    print("net", bk["net"], "halves", bk["halves_xs"]); print("long", bk["long"])
    print("f5", bk["frames"]["s3_plus_5bps"], "exact", bk["frames"]["s6_exact"])
    h = b["edge_decay"]["headline"]["GR1"]; print("plan", h["planning"], "floor", h["floor"])
    print("taa dead", b["edge_decay"]["scenarios"]["TAA dead"]["GR1"]["xs"], "edge margin", b["edge_decay"]["edge_margin"]["GR1"]["lowest_passing_k"], "minimax", b["edge_decay"]["minimax"])
    x = e["books"]["GR1"]; print("exp", x["nasdaq_lookthrough"]["max"], x["nasdaq_lookthrough"]["mean"], x["nasdaq_lookthrough"]["p90"], x["nasdaq_peak_date"], x["nasdaq_max_since_2015"], x["nasdaq_lookthrough_drift"]["max"], x["equity_exposure"], x["tbill_like_share"]["mean"])
    print("cap meta", json.dumps(c["meta"])[:600]); print("cap books", list(c["books"]))
    g1 = c["books"].get("GR1"); print(json.dumps(g1)[:2500])
    print("believe", b["believe"]["GR1"]); print("boot", {k: b["bootstrap"]["blocks"][k]["GR1"] for k in b["bootstrap"]["blocks"]}, b["bootstrap"]["horizons"]["756"]["GR1"], b["bootstrap"]["cagr"]["GR1"])
    print("reset", b["reset"]["GR1"]["start_month_spread"], b["reset"]["GR1"]["policies"]["annual"].get("max_capsule_share"))
    print("dep", {k: b["dependence"]["products"]["GR1"][k] for k in ("risk_share","excess_return_share","diversification_ratio","at_max_dd","months_all_three_lost")})
    print("margin", {k: (r["vol_matched"]["name"], r["cagr_matched"] and r["cagr_matched"]["name"]) for k, r in s["margin"].items()})
    print("blends", {k: (round(r["q"]["cagr"],4), round(r["q"]["xs"],3), round(r["q"]["dd"],4), r.get("defense_first_capital")) for k, r in s["blends"].items()})
    print("standins", {k: (r["rung"]["pass"], round(r["vs_s9"]["share_xs"],3), round(r["corr_with_gr1"],3)) for k, r in s["standins"].items()})
    print("construction", s["construction"])
    print("products", {k: (p["final"], p["fits_rung"], p["offered"], p["step_over_product_below"]) for k, p in s["products"].items()})
    print("def diff keys same?", json.dumps(d)[:300])
    print("after", b["after_window"]["books"].get("GR1")); print("loyo", b["loyo"]["GR1"]); print("rolling", b["rolling"]["GR1"])
    print("alpha GR1 long gross", [(a["model"], a) for a in b["alpha"] if a["book"]=="GR1" and a["window"]=="long" and a["basis"]=="gross"][:1])
    print("dial", {n: (round(s["books"][n]["q"]["cagr"],4), round(s["books"][n]["q"]["xs"],3), round(s["books"][n]["q"]["dd"],4), s["books"][n]["tails"]["p20"]) for n in s["dial"]})
